# Site settings
baseurl = "https://blog.lebiller.dev/"
languageCode = "en"
title = "Practical Thoughts"
theme = "hugo-theme-cactus-plus"
hasCJKLanguage = false
pygmentsUseClasses = false
pygmentsStyle = "friendly"
publishDir = "docs"

[markup.goldmark.renderer]
    unsafe = true

[params]
    author = "Guillaume Le Biller"
    description = "Any fool can know. The point is to understand."
    bio = "I am a curious and constantly learning engineer passionate about all technologies"

    enableRSS = false
    enableToc = false

    enableDisqus = false
    disqusShortname = "your_disqus_short_name"

    enableSummary = true
    useDescriptionReplaceSummary = false

    enableGoogleAnalytics = false

    enableTwitterCard = true
    twitterCardImage = ""

    # Navigation links
    home = ""
    about = ""
    archive = ""
    subscribe = ""

    olderPosts = ""
    newerPosts = ""
    copyright = ""

    showLatestPosts = false
    readMore = ""

    enableShare = false
    tweet = ""
    share = ""

    title404 = ""
    subtitle404 = ""

[social]
	github = "https://www.github.com/Kissy"
	linkedin = "https://www.linkedin.com/in/guillaume-le-biller-b1b38773/"
